import jsPDF from 'jspdf';
import type { WeeklyReport, GrowthPlan } from '@/hooks/useSpiritualGrowth';

const MARGIN = 20;
const PAGE_WIDTH = 210;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

function addWrappedText(doc: jsPDF, text: string, x: number, y: number, maxWidth: number, lineHeight: number): number {
  const lines = doc.splitTextToSize(text, maxWidth);
  for (const line of lines) {
    if (y > 275) { doc.addPage(); y = MARGIN; }
    doc.text(line, x, y);
    y += lineHeight;
  }
  return y;
}

function addSection(doc: jsPDF, title: string, body: string | null | undefined, y: number, color: [number, number, number] = [180, 160, 100]): number {
  if (!body) return y;
  if (y > 255) { doc.addPage(); y = MARGIN; }
  doc.setFontSize(11);
  doc.setTextColor(...color);
  doc.setFont('helvetica', 'bold');
  doc.text(title, MARGIN, y);
  y += 7;
  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  doc.setFont('helvetica', 'normal');
  y = addWrappedText(doc, body, MARGIN, y, CONTENT_WIDTH, 5);
  return y + 5;
}

export function exportWeeklyReportPdf(report: WeeklyReport) {
  const doc = new jsPDF();
  let y = MARGIN;

  // Header
  doc.setFontSize(18);
  doc.setTextColor(120, 100, 60);
  doc.setFont('helvetica', 'bold');
  doc.text('Ora — Weekly Spiritual Report', MARGIN, y);
  y += 8;
  doc.setFontSize(9);
  doc.setTextColor(130, 130, 130);
  doc.setFont('helvetica', 'normal');
  doc.text(`${report.week_start} — ${report.week_end}`, MARGIN, y);
  y += 4;
  doc.setDrawColor(200, 180, 120);
  doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
  y += 10;

  y = addSection(doc, 'This Week with God', report.overall_summary, y);
  y = addSection(doc, 'Where You Grew', report.growth_areas, y, [60, 150, 90]);
  y = addSection(doc, 'Where You Struggled', report.struggle_patterns, y, [200, 140, 60]);
  y = addSection(doc, 'God May Be Inviting You To…', report.divine_invitation, y, [80, 120, 200]);
  y = addSection(doc, 'Focus for Next Week', report.weekly_focus, y, [180, 160, 100]);

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(170, 170, 170);
  doc.text('Generated by Ora — Your Catholic AI Spiritual Companion', MARGIN, 290);

  doc.save(`ora-weekly-report-${report.week_start}.pdf`);
}

export function exportGrowthPlanPdf(plan: GrowthPlan) {
  const doc = new jsPDF();
  let y = MARGIN;

  // Header
  doc.setFontSize(18);
  doc.setTextColor(120, 100, 60);
  doc.setFont('helvetica', 'bold');
  doc.text('Ora — 3-Day Spiritual Growth Plan', MARGIN, y);
  y += 8;
  doc.setFontSize(12);
  doc.setTextColor(60, 60, 60);
  doc.text(plan.title, MARGIN, y);
  y += 6;
  if (plan.focus_area) {
    doc.setFontSize(9);
    doc.setTextColor(180, 160, 100);
    doc.text(`Focus: ${plan.focus_area}`, MARGIN, y);
    y += 4;
  }
  doc.setDrawColor(200, 180, 120);
  doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
  y += 10;

  const days = [
    { label: 'Day 1 — Action', text: plan.day1_action },
    { label: 'Day 2 — Prayer & Reflection', text: plan.day2_action },
    { label: 'Day 3 — Challenge', text: plan.day3_action },
  ];

  for (const day of days) {
    y = addSection(doc, day.label, day.text, y);
  }

  y = addSection(doc, 'Scripture Anchor', plan.scripture_anchor, y, [80, 120, 200]);
  y = addSection(doc, 'Prayer', plan.plan_prayer, y, [120, 100, 60]);

  doc.setFontSize(8);
  doc.setTextColor(170, 170, 170);
  doc.text('Generated by Ora — Your Catholic AI Spiritual Companion', MARGIN, 290);

  doc.save(`ora-growth-plan-${plan.start_date}.pdf`);
}
