import jsPDF from 'jspdf';
import type { WeeklyReport, GrowthPlan } from '@/hooks/useSpiritualGrowth';

const MARGIN = 20;
const PAGE_WIDTH = 210;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

function addWrappedText(doc: jsPDF, text: string, x: number, y: number, maxWidth: number, lineHeight: number): number {
  const lines = doc.splitTextToSize(text, maxWidth);
  for (const line of lines) {
    if (y > 275) { doc.addPage(); y = MARGIN; }
    doc.text(line, x, y);
    y += lineHeight;
  }
  return y;
}

function addSection(doc: jsPDF, title: string, body: string | null | undefined, y: number, color: [number, number, number] = [180, 160, 100]): number {
  if (!body) return y;
  if (y > 255) { doc.addPage(); y = MARGIN; }
  doc.setFontSize(11);
  doc.setTextColor(...color);
  doc.setFont('helvetica', 'bold');
  doc.text(title, MARGIN, y);
  y += 7;
  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  doc.setFont('helvetica', 'normal');
  y = addWrappedText(doc, body, MARGIN, y, CONTENT_WIDTH, 5);
  return y + 5;
}

export function exportWeeklyReportPdf(report: WeeklyReport) {
  const doc = new jsPDF();
  let y = MARGIN;

  // Header
  doc.setFontSize(18);
  doc.setTextColor(120, 100, 60);
  doc.setFont('helvetica', 'bold');
  doc.text('Ora — Weekly Spiritual Report', MARGIN, y);
  y += 8;
  doc.setFontSize(9);
  doc.setTextColor(130, 130, 130);
  doc.setFont('helvetica', 'normal');
  doc.text(`${report.week_start} — ${report.week_end}`, MARGIN, y);
  y += 4;
  doc.setDrawColor(200, 180, 120);
  doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
  y += 10;

  y = addSection(doc, 'This Week with God', report.overall_summary, y);
  y = addSection(doc, 'Where You Grew', report.growth_areas, y, [60, 150, 90]);
  y = addSection(doc, 'Where You Struggled', report.struggle_patterns, y, [200, 140, 60]);
  y = addSection(doc, 'God May Be Inviting You To…', report.divine_invitation, y, [80, 120, 200]);
  y = addSection(doc, 'Focus for Next Week', report.weekly_focus, y, [180, 160, 100]);

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(170, 170, 170);
  doc.text('Generated by Ora — Your Catholic AI Spiritual Companion', MARGIN, 290);

  doc.save(`ora-weekly-report-${report.week_start}.pdf`);
}

export function exportGrowthPlanPdf(plan: GrowthPlan) {
  const doc = new jsPDF();
  let y = MARGIN;

  // Header
  doc.setFontSize(18);
  doc.setTextColor(120, 100, 60);
  doc.setFont('helvetica', 'bold');
  doc.text('Ora — 3-Day Spiritual Growth Plan', MARGIN, y);
  y += 8;
  doc.setFontSize(12);
  doc.setTextColor(60, 60, 60);
  doc.text(plan.title, MARGIN, y);
  y += 6;
  if (plan.focus_area) {
    doc.setFontSize(9);
    doc.setTextColor(180, 160, 100);
    doc.text(`Focus: ${plan.focus_area}`, MARGIN, y);
    y += 4;
  }
  doc.setDrawColor(200, 180, 120);
  doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
  y += 10;

  const days = [
    { label: 'Day 1 — Action', text: plan.day1_action },
    { label: 'Day 2 — Prayer & Reflection', text: plan.day2_action },
    { label: 'Day 3 — Challenge', text: plan.day3_action },
  ];

  for (const day of days) {
    y = addSection(doc, day.label, day.text, y);
  }

  y = addSection(doc, 'Scripture Anchor', plan.scripture_anchor, y, [80, 120, 200]);
  y = addSection(doc, 'Prayer', plan.plan_prayer, y, [120, 100, 60]);

  doc.setFontSize(8);
  doc.setTextColor(170, 170, 170);
  doc.text('Generated by Ora — Your Catholic AI Spiritual Companion', MARGIN, 290);

  doc.save(`ora-growth-plan-${plan.start_date}.pdf`);
}

// ─── Prayer Path (per-day) export ────────────────────────────────────────────

export interface PrayerPathStageExport {
  title: string;
  body: string;
  completed: boolean;
  note?: string;
}

export interface PrayerPathExport {
  prayerType: 'morning' | 'midday' | 'night' | string;
  prayerTitle: string;     // e.g. "Morning Lauds"
  date: string;            // ISO YYYY-MM-DD
  stages: PrayerPathStageExport[];
}

/** Strip basic markdown so the PDF reads cleanly without rendering it. */
function stripMarkdown(md: string): string {
  return md
    .replace(/```[\s\S]*?```/g, '')           // code fences
    .replace(/`([^`]+)`/g, '$1')               // inline code
    .replace(/!\[[^\]]*\]\([^)]*\)/g, '')      // images
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')   // links → text
    .replace(/^#{1,6}\s+/gm, '')               // headings
    .replace(/(\*\*|__)(.*?)\1/g, '$2')        // bold
    .replace(/(\*|_)(.*?)\1/g, '$2')           // italic
    .replace(/^>\s?/gm, '')                    // blockquote
    .replace(/^[\-*+]\s+/gm, '• ')             // bullets
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function formatLongDate(iso: string): string {
  try {
    const [y, m, d] = iso.split('-').map(Number);
    return new Date(y, (m || 1) - 1, d || 1).toLocaleDateString(undefined, {
      weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
    });
  } catch { return iso; }
}

export function exportPrayerPathPdf(data: PrayerPathExport) {
  const doc = new jsPDF();
  let y = MARGIN;

  // Header
  doc.setFontSize(18);
  doc.setTextColor(120, 100, 60);
  doc.setFont('helvetica', 'bold');
  doc.text(`Ora — ${data.prayerTitle}`, MARGIN, y);
  y += 8;

  doc.setFontSize(10);
  doc.setTextColor(130, 130, 130);
  doc.setFont('helvetica', 'normal');
  doc.text(formatLongDate(data.date), MARGIN, y);
  y += 5;

  doc.setDrawColor(200, 180, 120);
  doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
  y += 8;

  // Summary line
  const total = data.stages.length;
  const done = data.stages.filter((s) => s.completed).length;
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`${done} of ${total} stage${total === 1 ? '' : 's'} completed today`, MARGIN, y);
  y += 9;

  if (total === 0) {
    doc.setFontSize(11);
    doc.setTextColor(80, 80, 80);
    doc.text('No prayer stages recorded for today yet.', MARGIN, y);
  }

  // Stages
  data.stages.forEach((stage, i) => {
    if (y > 255) { doc.addPage(); y = MARGIN; }

    // Title row with check indicator
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(stage.completed ? 120 : 130, stage.completed ? 100 : 130, stage.completed ? 60 : 130);
    const marker = stage.completed ? '✓ ' : '○ ';
    const titleLine = `${marker}Stage ${i + 1}  ·  ${stage.title || 'Untitled'}`;
    doc.text(titleLine, MARGIN, y);
    y += 7;

    // Body
    const body = stripMarkdown(stage.body || '');
    if (body) {
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(60, 60, 60);
      y = addWrappedText(doc, body, MARGIN, y, CONTENT_WIDTH, 5);
      y += 2;
    }

    // Reflection
    if (stage.note && stage.note.trim()) {
      if (y > 260) { doc.addPage(); y = MARGIN; }
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(120, 100, 60);
      doc.text('Reflection', MARGIN, y);
      y += 5;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(80, 80, 80);
      y = addWrappedText(doc, stage.note.trim(), MARGIN + 4, y, CONTENT_WIDTH - 4, 5);
      doc.setFont('helvetica', 'normal');
      y += 3;
    }

    // Divider between stages
    if (i < data.stages.length - 1) {
      doc.setDrawColor(230, 220, 200);
      doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
      y += 6;
    }
  });

  // Footer on every page
  const pageCount = doc.getNumberOfPages();
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p);
    doc.setFontSize(8);
    doc.setTextColor(170, 170, 170);
    doc.setFont('helvetica', 'normal');
    doc.text('Generated by Ora — Your Catholic AI Spiritual Companion', MARGIN, 290);
    doc.text(`${p} / ${pageCount}`, PAGE_WIDTH - MARGIN - 12, 290);
  }

  doc.save(`ora-${data.prayerType}-${data.date}.pdf`);
}
