project_id = "lrrsmihlulzuhdqndinw"

[functions.process-email-queue]
verify_jwt = true

[functions.saint-tts]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.get-paddle-price]
verify_jwt = false

[functions.paddle-portal]
verify_jwt = false

[functions.paddle-cancel]
verify_jwt = false

[functions.paddle-resume]
verify_jwt = false

[functions.paddle-update-plan]
verify_jwt = false

[functions.trial-reminders]
verify_jwt = false

[functions.send-transactional-email]
verify_jwt = true

[functions.preview-transactional-email]
verify_jwt = false

[functions.handle-email-unsubscribe]
verify_jwt = false

[functions.handle-email-suppression]
verify_jwt = false
