project_id = "lrrsmihlulzuhdqndinw"

[functions.process-email-queue]
verify_jwt = true

[functions.saint-tts]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.get-paddle-price]
verify_jwt = false

[functions.paddle-portal]
verify_jwt = false

[functions.paddle-cancel]
verify_jwt = false
